import express from 'express';
import crypto from 'crypto';
import { supabase } from '../db/supabase.js';
import { generateEmbedding } from '../services/gemini.js';

const router = express.Router();

// Helper to generate text representation
const generateItineraryText = (itinerary) => {
    const parts = [];
    if (itinerary.destination) parts.push(`Trip to ${itinerary.destination}`);
    if (itinerary.days) {
        itinerary.days.forEach(day => {
            parts.push(`Day ${day.day}: ${day.theme}`);
            if (day.activities) {
                day.activities.forEach(act => {
                    parts.push(`${act.time}: ${act.activity} at ${act.location}. ${act.description}`);
                });
            }
        });
    }
    return parts.join('\n');
};

// POST /api/itineraries/search - Search for similar itineraries
// Expects: { query: string } or { destination: string, interests: string[] }
router.post('/search', async (req, res) => {
    try {
        const { query, destination, interests } = req.body;
        console.log('Search request received:', { query, destination, interests });

        let searchText = query;
        if (!searchText && destination) {
            searchText = `Trip to ${destination}`;
            if (interests && interests.length > 0) {
                searchText += ` with interests: ${interests.join(', ')}`;
            }
        }

        if (!searchText) {
            return res.status(400).json({ error: 'Search query or destination required' });
        }

        console.log('Generating embedding for:', searchText);
        const embedding = await generateEmbedding(searchText);

        // Import dynamically to avoid circular dependencies if any, though here it's fine
        const { searchSimilarItineraries } = await import('../services/vectorService.js');

        console.log('Searching vector store...');
        const results = await searchSimilarItineraries(embedding, 0.6, 10); // Lower threshold for exploration, higher limit

        console.log(`Found ${results?.length || 0} matches`);
        res.json(results || []);
    } catch (error) {
        console.error('Error searching itineraries:', error);
        res.status(500).json({ error: 'Internal Server Error', details: error.message });
    }
});

// GET /api/itineraries/trending - Get trending/recent itineraries
router.get('/trending', async (req, res) => {
    try {
        // For now, just return the 10 most recently added itineraries
        const { data, error } = await supabase
            .from('itineraries')
            .select('id, metadata')
            .order('id', { ascending: false }) // Using UUID as proxy for time if no createdAt, or just random
            .limit(10);

        if (error) {
            throw error;
        }

        // Map to expected format if needed, but client handles metadata
        const results = data.map(item => ({
            id: item.id,
            ...item.metadata, // flatten if client expects metadata props at top level or match vector format
            metadata: item.metadata // keep metadata object for consistency with vector search result structure
        }));

        res.json(results);
    } catch (error) {
        console.error('Error fetching trending itineraries:', error);
        res.status(500).json({ error: 'Internal Server Error', details: error.message });
    }
});

// POST /api/itineraries - Save itinerary
router.post('/', async (req, res) => {

    const itineraryData = req.body;

    // Validate
    if (!itineraryData) {
        return res.status(400).json({ error: 'Itinerary data is required' });
    }

    const id = crypto.randomUUID();
    const createdAt = new Date().toISOString();

    try {
        const textContent = generateItineraryText(itineraryData);
        let embedding = null;
        try {
            embedding = await generateEmbedding(textContent);
        } catch (e) {
            console.error("Embedding generation failed, continuing without embedding:", e);
        }

        const { error } = await supabase
            .from('itineraries')
            .insert({
                id,
                content: textContent,
                metadata: itineraryData,
                embedding
            }); // createdAt is likely auto-generated by Supabase, or we can add it if column exists

        if (error) {
            throw error;
        }

        res.json({ id });
    } catch (error) {
        console.error('Error saving itinerary:', error);
        res.status(500).json({ error: 'Internal Server Error', details: error.message });
    }
});

// GET /api/itineraries/:id - Get itinerary
router.get('/:id', async (req, res) => {
    const { id } = req.params;

    try {
        const { data, error } = await supabase
            .from('itineraries')
            .select('metadata')
            .eq('id', id)
            .single();

        if (error) {
            if (error.code === 'PGRST116') { // Not found code often returned by single()
                return res.status(404).json({ error: 'Itinerary not found' });
            }
            throw error;
        }

        if (!data) {
            return res.status(404).json({ error: 'Itinerary not found' });
        }

        res.json(data.metadata);
    } catch (error) {
        console.error('Error fetching itinerary:', error);
        res.status(500).json({ error: 'Internal Server Error', details: error.message });
    }
});

export default router;
